name: Tags

on:
  push:
    tags:
      - 'prettier-config-pretto@*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
